Repository ITC-CRIB/jupyter-fairly, pull requests merged in 2022-11, with the labels that each got.

#55 Alpha version for JupyterLab extension
  jupyterfair/jupyterfair/handlers.py
  jupyterfair/src/dataset.ts
  jupyterfair/src/widgets/CloneForm.ts
Labels: enhancement

#56 Update dependencies
  jupyterfair/jupyterfair/handlers.py
  jupyterfair/yarn.lock
Labels: dependencies

#58 Feature/handlers
  README.md
  docs/img/contex-menu.png
  jupyterfair/jupyterfair/handlers.py
  jupyterfair/package.json
  jupyterfair/setup.py
  jupyterfair/src/dataset.ts
  jupyterfair/src/index.ts
  jupyterfair/src/logger.ts
  jupyterfair/src/metadata.ts
  jupyterfair/src/tokens.ts
  jupyterfair/src/upload.ts
  jupyterfair/src/widgets/CloneForm.ts
  jupyterfair/src/widgets/FairlyTab.ts
  jupyterfair/src/widgets/panel.ts
Labels: enhancement

#59 Fix typo
  docs/package/installation.rst
Labels: documentation
